CREATE DATABASE Futbol;
USE Futbol;

CREATE TABLE Liga (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Nombre VARCHAR(100) NOT NULL,
  Pais VARCHAR(50) NOT NULL,
  Equipos INT NOT NULL DEFAULT 0,
  EquiposMax INT NOT NULL DEFAULT 20,
  CONSTRAINT uqLigaNombrePais UNIQUE (Nombre, Pais)
);
 
CREATE TABLE Equipo (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Nombre VARCHAR(120) NOT NULL,
  LigaID INT,
  CONSTRAINT uqEquipoNombreLiga UNIQUE (Nombre, LigaID),
  CONSTRAINT fkEquipoLiga FOREIGN KEY (LigaID) REFERENCES Liga(ID)
    ON UPDATE CASCADE ON DELETE SET NULL
);
 
CREATE TABLE Entrenador (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Nombre VARCHAR(60) NOT NULL,
  Apellido VARCHAR(60) NOT NULL,
  Nacionalidad VARCHAR(50),
  EquipoID INT,
  CONSTRAINT uqEntrenadorEquipo UNIQUE (EquipoID),
  CONSTRAINT fkEntrenadorEquipo FOREIGN KEY (EquipoID) REFERENCES Equipo(ID)
    ON UPDATE CASCADE ON DELETE SET NULL
);
 
CREATE TABLE Jugador (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Nombre VARCHAR(60) NOT NULL,
  Apellido VARCHAR(60) NOT NULL,
  Nacionalidad VARCHAR(50),
  EquipoID INT,
  CONSTRAINT fkJugadorEquipo FOREIGN KEY (EquipoID) REFERENCES Equipo(ID)
    ON UPDATE CASCADE ON DELETE SET NULL
);
 
CREATE TABLE Posicion (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Nombre VARCHAR(50) NOT NULL,
  CONSTRAINT uqPosicionNombre UNIQUE (Nombre)
);
 
CREATE TABLE JugadorPosicion (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  JugadorID INT NOT NULL,
  PosicionID INT NOT NULL,
  CONSTRAINT uqJugadorPosicion UNIQUE (JugadorID, PosicionID),
  CONSTRAINT fkJPJugador FOREIGN KEY (JugadorID) REFERENCES Jugador(ID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fkJPPosicion FOREIGN KEY (PosicionID) REFERENCES Posicion(ID)
    ON DELETE RESTRICT ON UPDATE CASCADE
);
